CREATE TABLE IF NOT EXISTS DataItem (
    screenId INTEGER NOT NULL DEFAULT 0,
    timestamp INTEGER NOT NULL PRIMARY KEY,
    data TEXT DEFAULT NULL,
    status INTEGER NOT NULL DEFAULT 0,
    error TEXT DEFAULT NULL,
    ocr Text DEFAULT NULL,
    mark TEXT DEFAULT NULL
);